'use client'

import Link from 'next/link'
import { motion } from 'framer-motion'
import dynamic from 'next/dynamic'
import { ArrowRight, Mic, Brain, FileText, BarChart3, ChevronDown } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useState } from 'react'

const VoiceOrb = dynamic(
  () => import('@/components/interview/VoiceOrb').then(m => m.VoiceOrb),
  { ssr: false }
)

const FEATURES = [
  {
    icon: Mic,
    title: 'Voice-first',
    desc: 'Real-time voice conversation with sub-800ms latency. Feels like a real interview, not a chat bot.',
    color: 'var(--accent-violet)',
  },
  {
    icon: Brain,
    title: 'Role-specific',
    desc: 'Six interview types: Frontend, Backend, Full-Stack, System Design, Behavioral, DSA.',
    color: 'var(--accent-cyan)',
  },
  {
    icon: FileText,
    title: 'Resume-aware',
    desc: 'Upload your resume and ARIA personalises questions based on your experience.',
    color: '#F59E0B',
  },
  {
    icon: BarChart3,
    title: 'Instant feedback',
    desc: 'Detailed score breakdown with radar chart, strengths, weaknesses, and action items.',
    color: '#10B981',
  },
]

const STEPS = [
  { n: '01', title: 'Pick your interview', desc: 'Choose role, difficulty, and duration.' },
  { n: '02', title: 'Talk to ARIA',         desc: 'Voice-first AI conducts a rigorous mock interview.' },
  { n: '03', title: 'Get your report',      desc: 'Detailed scored feedback within seconds of finishing.' },
]

const FAQS = [
  { q: 'Is it free?',                 a: 'Yes. ARIA is free to use. Vapi free credits give you ~100 minutes of voice calls.' },
  { q: 'How realistic are questions?', a: 'Questions are dynamically generated by GPT-4o-mini tailored to your role and difficulty level.' },
  { q: 'Can I upload my resume?',     a: 'Yes — ARIA uses it to ask personalised questions about your specific experience.' },
  { q: 'What languages are supported?', a: 'English only at the moment. Multi-language support is planned.' },
]

function FaqItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false)
  return (
    <div className="card-elevated overflow-hidden">
      <button onClick={() => setOpen(!open)} className="w-full flex items-center justify-between p-5 text-left">
        <span className="font-medium text-sm">{q}</span>
        <ChevronDown className="w-4 h-4 transition-transform duration-200 flex-shrink-0"
          style={{ transform: open ? 'rotate(180deg)' : '', color: 'var(--text-secondary)' }} />
      </button>
      {open && (
        <div className="px-5 pb-5 text-sm" style={{ color: 'var(--text-secondary)' }}>{a}</div>
      )}
    </div>
  )
}

const stagger = {
  container: { animate: { transition: { staggerChildren: 0.1 } } },
  item: {
    initial:  { opacity: 0, y: 24 },
    animate:  { opacity: 1, y: 0, transition: { duration: 0.6, ease: 'easeOut' as const } },
  },
}

export default function LandingPage() {
  return (
    <div style={{ background: 'var(--bg-base)' }}>
      {/* Nav */}
      <nav className="fixed top-0 inset-x-0 z-50 glass">
        <div className="max-w-6xl mx-auto px-6 h-14 flex items-center justify-between">
          <span className="text-lg font-bold gradient-text">ARIA</span>
          <div className="flex items-center gap-3">
            <Link href="/login">
              <Button variant="ghost" size="sm">Sign in</Button>
            </Link>
            <Link href="/register">
              <Button size="sm" style={{ background: 'var(--accent-gradient)' }}>Get started free</Button>
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative min-h-screen flex flex-col items-center justify-center text-center px-6 pt-20">
        {/* Orb background */}
        <div className="absolute inset-0 flex items-center justify-center opacity-30 pointer-events-none">
          <VoiceOrb isSpeaking={false} volumeLevel={0.3} size={500} />
        </div>

        <motion.div variants={stagger.container} initial="initial" animate="animate"
          className="relative z-10 max-w-3xl mx-auto">
          <motion.div variants={stagger.item}>
            <span className="inline-block text-xs font-medium tracking-widest px-3 py-1 rounded-full mb-6"
              style={{ background: 'rgba(139,92,246,0.15)', border: '1px solid rgba(139,92,246,0.3)', color: 'var(--accent-violet)' }}>
              VOICE-FIRST AI INTERVIEWS
            </span>
          </motion.div>

          <motion.h1 variants={stagger.item}
            className="text-5xl md:text-7xl font-bold leading-[1.08] tracking-tight mb-6">
            Practice interviews{' '}
            <span className="gradient-text">that feel real.</span>
          </motion.h1>

          <motion.p variants={stagger.item}
            className="text-lg md:text-xl mb-10 max-w-xl mx-auto leading-relaxed"
            style={{ color: 'var(--text-secondary)' }}>
            ARIA conducts voice-first mock interviews, asks follow-ups like a real interviewer,
            and gives you scored feedback in seconds.
          </motion.p>

          <motion.div variants={stagger.item} className="flex items-center justify-center gap-4 flex-wrap">
            <Link href="/register">
              <Button size="lg" className="gap-2 glow-violet"
                style={{ background: 'var(--accent-gradient)', fontSize: '1rem' }}>
                Start free interview <ArrowRight className="w-4 h-4" />
              </Button>
            </Link>
            <a href="#how-it-works">
              <Button size="lg" variant="outline" className="text-base">
                How it works
              </Button>
            </a>
          </motion.div>
        </motion.div>
      </section>

      {/* Features bento */}
      <section className="py-24 px-6 max-w-5xl mx-auto">
        <motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }} viewport={{ once: true }}
          className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">Built for serious prep.</h2>
          <p style={{ color: 'var(--text-secondary)' }}>Everything you need to ace your next interview.</p>
        </motion.div>

        <div className="grid md:grid-cols-2 gap-4">
          {FEATURES.map((f, i) => (
            <motion.div key={f.title}
              initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: i * 0.08 }} viewport={{ once: true }}
              className="card-elevated p-7 group hover:-translate-y-1 transition-transform duration-300 cursor-default"
              style={{ '--hover-color': f.color } as React.CSSProperties}>
              <div className="w-11 h-11 rounded-xl flex items-center justify-center mb-5"
                style={{ background: `${f.color}18`, border: `1px solid ${f.color}30` }}>
                <f.icon className="w-5 h-5" style={{ color: f.color }} />
              </div>
              <h3 className="font-semibold text-lg mb-2">{f.title}</h3>
              <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section id="how-it-works" className="py-24 px-6">
        <div className="max-w-5xl mx-auto">
          <motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }} viewport={{ once: true }}
            className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">Three steps to better interviews.</h2>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-6">
            {STEPS.map((s, i) => (
              <motion.div key={s.n}
                initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: i * 0.1 }} viewport={{ once: true }}
                className="card-elevated p-7">
                <span className="text-5xl font-bold gradient-text opacity-40">{s.n}</span>
                <h3 className="font-semibold mt-4 mb-2">{s.title}</h3>
                <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>{s.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-24 px-6 max-w-2xl mx-auto">
        <motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }} viewport={{ once: true }}
          className="text-center mb-12">
          <h2 className="text-3xl font-bold">FAQ</h2>
        </motion.div>
        <div className="space-y-3">
          {FAQS.map(faq => <FaqItem key={faq.q} {...faq} />)}
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-6 text-center">
        <motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }} viewport={{ once: true }}>
          <h2 className="text-4xl md:text-5xl font-bold mb-6">
            Ready to practice <span className="gradient-text">like it&apos;s real?</span>
          </h2>
          <Link href="/register">
            <Button size="lg" style={{ background: 'var(--accent-gradient)', fontSize: '1rem' }}
              className="gap-2 glow-violet">
              Start for free <ArrowRight className="w-4 h-4" />
            </Button>
          </Link>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="border-t py-8 px-6 text-center text-xs"
        style={{ borderColor: 'var(--border-subtle)', color: 'var(--text-secondary)' }}>
        © 2026 ARIA. Built with Next.js, Supabase & Vapi.
      </footer>
    </div>
  )
}
